import os
import csv
import json
import requests
import random
from datetime import datetime, timedelta
from typing import Dict, Any

# ==========================================
# CONFIG
# ==========================================

# Ensure you have exported GOOGLE_MAPS_API_KEY
API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY")

# Maximum crawl limit (safety cap to avoid infinite loops)
MAX_CRAWLS = 200
# Stop when enough valid webpages have been collected
MIN_WEBPAGES = 20

# Optional: set to get real events from Ticketmaster (free tier)
TICKETMASTER_API_KEY = os.environ.get("TICKETMASTER_API_KEY")
# Optional: set to get real train/bus schedules from PTV (Public Transport Victoria)
PTV_DEV_ID = os.environ.get("PTV_DEV_ID")
PTV_API_KEY = os.environ.get("PTV_API_KEY")

CITY = "newyork"  # [london, tokyo, paris, newyork, "melbourne"]
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
NAME_DATASET_PATH = os.path.join(SCRIPT_DIR, "name_dataset.csv")
LANDMARKS_CSV_PATH = os.path.join(SCRIPT_DIR, "pois", f"{CITY}_pois.csv")
# Cache created by place_crawler.py (run once beforehand)
PLACES_CACHE_PATH = os.path.join(SCRIPT_DIR, f"places_cache_{CITY}.json")

# ==========================================
# DATA LOADERS
# ==========================================

def load_name_dataset() -> list:
    """Read names from name_dataset.csv."""
    names = []
    with open(NAME_DATASET_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            names.append({"name": row["name"], "sex": row["sex"]})
    return names

def load_landmarks() -> list:
    """Read landmarks from landmarks CSV + Monash University Clayton Campus."""
    landmarks = ["Monash University Clayton Campus"]
    with open(LANDMARKS_CSV_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row.get("Feature Name", "").strip()
            if name:
                landmarks.append(name)
    return landmarks

def load_places_cache() -> dict:
    """Read places_cache.json generated by place_crawler.py."""
    if os.path.exists(PLACES_CACHE_PATH):
        with open(PLACES_CACHE_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"landmarks": {}, "by_id": {}}

def save_places_cache(cache: dict):
    """Save cache (after adding places found along the route)."""
    with open(PLACES_CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)

def generate_australian_phone() -> str:
    """Generate a random Australian mobile phone number in 04XX XXX XXX format."""
    digits = "".join([str(random.randint(0, 9)) for _ in range(8)])
    return f"04{digits[:2]} {digits[2:5]} {digits[5:8]}"

# ==========================================
# GOOGLE AND JINA API CALLS
# ==========================================

def fetch_text_search(query: str, max_results: int = 3) -> list:
    """Free-text search for places to get Place IDs."""
    print(f"[*] Searching for: '{query}'...")
    url = "https://places.googleapis.com/v1/places:searchText"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        "X-Goog-FieldMask": "places.id" # Only fetch ID to save payload size
    }
    payload = {
        "textQuery": query,
        "languageCode": "en",
        "maxResultCount": max_results
    }
    
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        places = response.json().get("places", [])
        print(f"  -> Found {len(places)} places.")
        return [p["id"] for p in places]
    else:
        print(f"  [!] Text Search Error: {response.text}")
        return []

def fetch_compute_route(origin: dict, dest: dict, travel_mode: str = "DRIVE") -> dict:
    """Calculate routes and retrieve the actual polyline."""
    print(f"[*] Fetching route from {origin} to {dest}...")
    url = "https://routes.googleapis.com/directions/v2:computeRoutes"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        "X-Goog-FieldMask": "routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline"
    }
    payload = {
        "origin": {"location": {"latLng": {"latitude": origin["lat"], "longitude": origin["lng"]}}},
        "destination": {"location": {"latLng": {"latitude": dest["lat"], "longitude": dest["lng"]}}},
        "travelMode": travel_mode
    }
    
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        routes = response.json().get("routes", [])
        if routes:
            print("  -> Route retrieved successfully.")
            return routes[0]
    print(f"  [!] Error fetching route: {response.text}")
    return {}

def fetch_search_along_route(polyline: str, query: str) -> list:
    """Find places (place_ids) along the Polyline."""
    print(f"[*] Searching for '{query}' along the route...")
    url = "https://places.googleapis.com/v1/places:searchText"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        "X-Goog-FieldMask": "places.id"
    }
    payload = {
        "textQuery": query,
        "searchAlongRouteParameters": {
            "polyline": {"encodedPolyline": polyline}
        }
    }
    
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        places = response.json().get("places", [])
        print(f"  -> Found {len(places)} places along the route.")
        return [p["id"] for p in places]
    print(f"  [!] Search Along Route Error: {response.text}")
    return []

def fetch_place_details(place_id: str) -> Dict[str, Any]:
    """Retrieve comprehensive details using Place ID."""
    print(f"[*] Fetching details for Place ID: {place_id}...")
    url = f"https://places.googleapis.com/v1/places/{place_id}"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        # REQUEST EXTENSIVE FIELD SET
        "X-Goog-FieldMask": (
            "id,displayName,formattedAddress,location,types,"
            "rating,userRatingCount,priceLevel,websiteUri,nationalPhoneNumber,"
            "regularOpeningHours.weekdayDescriptions,regularOpeningHours.openNow,businessStatus,"
            "accessibilityOptions,allowsDogs,goodForChildren,servesVegetarianFood,outdoorSeating,reviews"
        )
    }
    
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"  [!] Place Details Error: {response.text}")
        return {}

# Jina patterns for non-existent pages / errors
_WEBPAGE_INVALID_PREFIXES = (
    "not found",
    "404",
    "page not found",
    "error",
    "access denied",
    "403 forbidden",
    "this site can\u2019t be reached",
    "this page isn",
)

def _is_valid_webpage(content: str) -> bool:
    """Returns False if content is an error / not found page."""
    if not content or len(content.strip()) < 100:
        return False
    first_line = content.strip().splitlines()[0].lower()
    return not any(first_line.startswith(p) for p in _WEBPAGE_INVALID_PREFIXES)

def fetch_webpage_content(url: str) -> str:
    """Use Jina Reader to crawl Markdown from the venue's website."""
    print(f"[*] Crawling website content: {url}...")
    jina_url = f"https://r.jina.ai/{url}"
    try:
        response = requests.get(jina_url, timeout=20)
        if response.status_code == 200:
            content = response.text[:4000]
            if not _is_valid_webpage(content):
                print("  [~] Invalid content (Not found / error), skipping.")
                return ""
            print("  -> Success.")
            return content
        else:
            print(f"  [!] Web crawl error: HTTP {response.status_code}")
            return ""
    except Exception as e:
        print(f"  [!] Web crawl Timeout/Connection error: {e}")
        return ""

def generate_fake_slots() -> Dict[str, int]:
    """Create mock data for available_slots with various times and slot counts."""
    # Realistic service hours for restaurants/cafes
    possible_times = ["08:00", "09:00", "10:30", "12:00", "12:30", "13:00",
                      "14:00", "17:00", "17:30", "18:00", "18:30", "19:00",
                      "19:30", "20:00", "20:30", "21:00"]
    slots = {}
    today = datetime.now()
    num_days = random.randint(2, 5)  # Next 2-5 days
    for day_offset in range(num_days):
        target_date = today + timedelta(days=day_offset)
        date_str = target_date.strftime("%Y-%m-%d")
        # Each day has 2-5 random time slots
        day_times = sorted(random.sample(possible_times, k=random.randint(2, 5)))
        for t in day_times:
            # Evenings are busier than lunchtime
            if t >= "17:00":
                slots[f"{date_str} {t}"] = random.choice([0, 0, 2, 4, 4, 6, 8, 10])
            else:
                slots[f"{date_str} {t}"] = random.choice([2, 4, 6, 8, 10, 12])
    return slots


# Realistic Melbourne tram and bus routes
_MELB_TRAM_ROUTES = ["1", "3/3a", "5", "6", "8", "11", "12", "16", "19",
                     "57", "58", "59", "64", "67", "70", "72", "75", "86", "96"]
_MELB_BUS_ROUTES = ["220", "246", "401", "402", "411", "546", "600", "601",
                     "605", "630", "703", "733", "900", "903", "905", "907"]
_MELB_TRAIN_LINES = ["Cranbourne", "Pakenham", "Glen Waverley", "Alamein",
                     "Lilydale", "Belgrave", "Frankston", "Sandringham",
                     "Werribee", "Williamstown", "Upfield", "Craigieburn",
                     "Sunbury", "Mernda", "Hurstbridge"]
_MELB_STOPS = [
    "Flinders Street Station", "Southern Cross Station", "Melbourne Central",
    "Flagstaff Station", "Parliament Station", "Caulfield Station",
    "Clayton Station", "Huntingdale Station", "Dandenong Station",
    "Footscray Station", "Sunshine Station", "Box Hill Station",
    "Ringwood Station", "Frankston Station", "Epping Station",
    "Clifton Hill", "North Melbourne Station", "Ascot Vale",
]

_TRANSIT_TYPES = [
    ("Tram", _MELB_TRAM_ROUTES),
    ("Bus", _MELB_BUS_ROUTES),
    ("Train", _MELB_TRAIN_LINES),
]


def _fetch_ptv_departures(stop_lat: float, stop_lng: float, dest_name: str) -> list:
    """Fetch real schedules from PTV API if key is available. Returns [] otherwise."""
    if not PTV_DEV_ID or not PTV_API_KEY:
        return []
    import hashlib, hmac, urllib.parse
    # PTV uses HMAC-SHA1 signature
    base_url = "/v3/stops/location/{lat},{lng}?max_results=1".format(lat=stop_lat, lng=stop_lng)
    raw = f"{base_url}\n" if "\n" not in base_url else base_url
    signature = hmac.new(
        PTV_API_KEY.encode("utf-8"), (base_url + f"?devid={PTV_DEV_ID}").encode("utf-8"),
        hashlib.sha1
    ).hexdigest().upper()
    url = f"https://timetableapi.ptv.vic.gov.au{base_url}&devid={PTV_DEV_ID}&signature={signature}"
    try:
        resp = requests.get(url, timeout=10)
        if resp.status_code == 200:
            stops = resp.json().get("stops", [])
            if stops:
                stop_id = stops[0]["stop_id"]
                route_type = stops[0].get("route_type", 1)
                # Fetch departures for this stop
                dep_url = f"/v3/departures/route_type/{route_type}/stop/{stop_id}?max_results=5&devid={PTV_DEV_ID}"
                sig2 = hmac.new(
                    PTV_API_KEY.encode("utf-8"), dep_url.encode("utf-8"), hashlib.sha1
                ).hexdigest().upper()
                full_dep_url = f"https://timetableapi.ptv.vic.gov.au{dep_url}&signature={sig2}"
                dep_resp = requests.get(full_dep_url, timeout=10)
                if dep_resp.status_code == 200:
                    deps = dep_resp.json().get("departures", [])
                    results = []
                    for d in deps[:5]:
                        sched = d.get("scheduled_departure_utc", "")
                        if sched:
                            dt = datetime.fromisoformat(sched.replace("Z", "+00:00"))
                            local_time = dt.strftime("%H:%M")
                        else:
                            local_time = "N/A"
                        results.append({
                            "route_number": str(d.get("route_id", "?")),
                            "destination": dest_name,
                            "departure_time": local_time,
                            "source": "PTV"
                        })
                    if results:
                        print("  -> Successfully fetched real schedule from PTV API.")
                        return results
    except Exception as e:
        print(f"  [~] PTV API error: {e}, falling back to fake data.")
    return []


def generate_fake_transit(db_data: dict, transit_nodes: list):
    """
    Generate diverse public transit schedules (train/tram/bus) based on coordinates.
    Prioritize PTV API if key exists, fallback to realistic Melbourne fake data.
    transit_nodes: [{"id": "ChIJ...", "name": "...", "dest_name": "...",
                     "lat": float, "lng": float}]
    """
    today = datetime.now()
    dates = [(today + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(3)]  # 3-day pool

    for node in transit_nodes:
        place_id = node["id"]
        dest_name = node["dest_name"]
        lat = node.get("lat")
        lng = node.get("lng")

        # Try to fetch real data from PTV if coordinates and key are available
        real_schedules = []
        if lat and lng:
            real_schedules = _fetch_ptv_departures(lat, lng, dest_name)

        db_data["transit_schedules"][place_id] = {}
        for date_str in dates:
            if real_schedules:
                db_data["transit_schedules"][place_id][date_str] = real_schedules
            else:
                print(f"[*] Generating fake transit schedule for {node['name']} on {date_str}...")
                # Diverse fake data: random selection of transit types
                schedule = []
                num_services = random.randint(3, 6)
                used_times = set()
                for _ in range(num_services):
                    transit_type, route_pool = random.choice(_TRANSIT_TYPES)
                    route = random.choice(route_pool)
                    # Generate unique departure times
                    for _attempt in range(10):
                        hour = random.randint(6, 22)
                        minute = random.choice([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
                        dep_time = f"{hour:02d}:{minute:02d}"
                        if dep_time not in used_times:
                            used_times.add(dep_time)
                            break
                    dest = dest_name if random.random() < 0.4 else random.choice(_MELB_STOPS)
                    schedule.append({
                        "type": transit_type,
                        "route_number": route,
                        "destination": dest,
                        "departure_time": dep_time
                    })
                # Sort by departure time
                schedule.sort(key=lambda x: x["departure_time"])
                db_data["transit_schedules"][place_id][date_str] = schedule


# Pool of diverse event data by theme
_EVENT_TEMPLATES = [
    {
        "name": "Melbourne Food & Wine Festival",
        "price_range": (0.0, 85.0),
        "category": "Food & Drink",
        "desc_tpl": "Celebrating the best of Melbourne's culinary scene at {place}."
    },
    {
        "name": "Live Jazz Night",
        "price_range": (0.0, 30.0),
        "category": "Music",
        "desc_tpl": "An intimate evening of live jazz performances at {place}."
    },
    {
        "name": "Urban Tech Meetup",
        "price_range": (0.0, 0.0),
        "category": "Networking",
        "desc_tpl": "Networking event for tech professionals hosted at {place}."
    },
    {
        "name": "AI & Smart City Workshop",
        "price_range": (20.0, 60.0),
        "category": "Education",
        "desc_tpl": "Hands-on workshop covering AI applications in urban planning."
    },
    {
        "name": "Sunday Farmers Market",
        "price_range": (0.0, 0.0),
        "category": "Market",
        "desc_tpl": "Local produce and artisan goods market at {place}."
    },
    {
        "name": "Heritage Walking Tour",
        "price_range": (5.0, 25.0),
        "category": "Culture",
        "desc_tpl": "Guided tour of Melbourne's historic architecture starting from {place}."
    },
    {
        "name": "Rooftop Cinema Screening",
        "price_range": (15.0, 35.0),
        "category": "Entertainment",
        "desc_tpl": "Open-air movie night with skyline views near {place}."
    },
    {
        "name": "Community Sports Day",
        "price_range": (0.0, 10.0),
        "category": "Sports",
        "desc_tpl": "Free community sports activities and games at {place}."
    },
    {
        "name": "Sustainability & Green Living Expo",
        "price_range": (0.0, 20.0),
        "category": "Environment",
        "desc_tpl": "Showcasing eco-friendly products and urban sustainability initiatives."
    },
    {
        "name": "Photography Pop-Up Exhibition",
        "price_range": (0.0, 15.0),
        "category": "Arts",
        "desc_tpl": "Local photographers display their work in and around {place}."
    },
]
_EVENT_TIMES = ["09:00", "10:00", "11:00", "12:00", "13:00", "14:00",
                "15:00", "16:00", "17:30", "18:00", "18:30", "19:00", "20:00"]


def _fetch_ticketmaster_events(lat: float, lng: float) -> list:
    """Fetch real events from Ticketmaster Discovery API if key is available."""
    if not TICKETMASTER_API_KEY:
        return []
    url = "https://app.ticketmaster.com/discovery/v2/events.json"
    params = {
        "apikey": TICKETMASTER_API_KEY,
        "latlong": f"{lat},{lng}",
        "radius": "5",
        "unit": "km",
        "size": "5",
        "sort": "date,asc",
        "countryCode": "AU"
    }
    try:
        resp = requests.get(url, params=params, timeout=10)
        if resp.status_code == 200:
            items = resp.json().get("_embedded", {}).get("events", [])
            results = []
            for ev in items:
                date_info = ev.get("dates", {}).get("start", {})
                results.append({
                    "event_name": ev.get("name", "Event"),
                    "date": date_info.get("localDate", ""),
                    "time": date_info.get("localTime", "19:00")[:5],
                    "ticket_price": ev.get("priceRanges", [{}])[0].get("min", 0.0) if ev.get("priceRanges") else 0.0,
                    "description": ev.get("info") or ev.get("pleaseNote") or f"Event at Melbourne: {ev.get('name', '')}",
                    "url": ev.get("url", ""),
                    "source": "Ticketmaster"
                })
            if results:
                print(f"  -> Fetched {len(results)} real events from Ticketmaster.")
                return results
    except Exception as e:
        print(f"  [~] Ticketmaster API error: {e}, falling back to fake data.")
    return []


def generate_fake_events(db_data: dict, place_nodes: list):
    """
    Generate diverse events based on location.
    Prioritize Ticketmaster API if key exists, fallback to a diverse fake pool.
    place_nodes: [{"id": "...", "name": "...", "lat": float, "lng": float}]
    """
    today = datetime.now()
    dates = [(today + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(7)]  # 7-day pool

    for item in place_nodes:
        pid = item["id"]
        pname = item["name"]
        lat = item.get("lat")
        lng = item.get("lng")

        # Try to fetch real events
        real_events = []
        if lat and lng:
            real_events = _fetch_ticketmaster_events(lat, lng)

        if real_events:
            db_data["events"][pid] = real_events
        else:
            print(f"[*] Generating fake events for {pname}...")
            # Fake: randomly select 2-4 events from pool
            chosen_templates = random.sample(_EVENT_TEMPLATES, k=random.randint(2, 4))
            event_list = []
            used_dates = set()
            for tmpl in chosen_templates:
                # Distribute unique dates
                available_dates = [d for d in dates if d not in used_dates]
                if not available_dates:
                    available_dates = dates
                event_date = random.choice(available_dates)
                used_dates.add(event_date)
                min_price, max_price = tmpl["price_range"]
                price = round(random.uniform(min_price, max_price) / 5) * 5 if max_price > 0 else 0.0
                event_list.append({
                    "event_name": tmpl["name"] if "{place}" not in tmpl["name"] else tmpl["name"].format(place=pname),
                    "category": tmpl["category"],
                    "date": event_date,
                    "time": random.choice(_EVENT_TIMES),
                    "ticket_price": price,
                    "description": tmpl["desc_tpl"].format(place=pname)
                })
            # Sort by date
            event_list.sort(key=lambda x: x["date"])
            db_data["events"][pid] = event_list


# ==========================================
# MAIN WORKFLOW
# ==========================================

def build_database(min_webpages: int = MIN_WEBPAGES, max_crawls: int = MAX_CRAWLS):
    if not API_KEY:
        print("Please set the GOOGLE_MAPS_API_KEY environment variable before running.")
        return

    # Load datasets only once
    all_names = load_name_dataset()
    all_landmarks = load_landmarks()

    # Load places cache (pre-generated by place_crawler.py)
    places_cache = load_places_cache()
    cached_landmarks = {name for name, pid in places_cache["landmarks"].items() if pid is not None}
    # Only use cached landmarks to avoid API calls
    available_landmarks = [lm for lm in all_landmarks if lm in cached_landmarks]
    if not available_landmarks:
        print("[!] places_cache.json is empty or does not exist.")
        print("    Please run place_crawler.py first: python place_crawler.py")
        return
    print(f"[Config] Target: {min_webpages} webpages | max {max_crawls} crawls | {len(available_landmarks)} landmarks (cached)")

    # Initialize aggregate db_data (shared across all crawls)
    db_data = {
        "places": {},
        "webpages": {},
        "users": {},
        "bookings": {},
        "routes": {},
        "search_along_routes": {},
        "transit_schedules": {},
        "events": {},
        "council_reports": {}
    }

    crawl_idx = 0
    while len(db_data["webpages"]) < min_webpages and crawl_idx < max_crawls:
        current_webpages = len(db_data["webpages"])
        print(f"\n{'='*60}")
        print(f"CRAWL ITERATION {crawl_idx + 1} | Webpages: {current_webpages}/{min_webpages}")
        print(f"{'='*60}")

        # --- Generate Random User ---
        user_info = random.choice(all_names)
        user_id = f"user_{crawl_idx + 1:03d}"
        user_phone = generate_australian_phone()
        db_data["users"][user_id] = {
            "user_id": user_id,
            "name": user_info["name"],
            "phone": user_phone
        }
        print(f"[User] {user_id}: {user_info['name']} ({user_phone})")

        # --- Randomly select Origin and Dest from cached list ---
        origin_query, dest_query = random.sample(available_landmarks, 2)

        print("\n--- STEP 1: READ LANDMARKS FROM CACHE ---")
        print(f"  Origin : {origin_query}")
        print(f"  Dest   : {dest_query}")

        place_ids_to_process = set()

        origin_id = places_cache["landmarks"][origin_query]
        dest_id = places_cache["landmarks"][dest_query]
        place_ids_to_process.update([origin_id, dest_id])

        origin_details = places_cache["by_id"].get(origin_id, {})
        dest_details = places_cache["by_id"].get(dest_id, {})

        if not origin_details or not dest_details:
            print("  [!] Cache missing details for landmark, skipping this iteration.")
            continue

        origin_name = origin_details.get("displayName", {}).get("text", "Origin")
        dest_name = dest_details.get("displayName", {}).get("text", "Destination")

        origin_lat = origin_details.get("location", {}).get("latitude")
        origin_lng = origin_details.get("location", {}).get("longitude")
        dest_lat = dest_details.get("location", {}).get("latitude")
        dest_lng = dest_details.get("location", {}).get("longitude")

        if None in (origin_lat, origin_lng, dest_lat, dest_lng):
            print("  [!] Missing coordinates in cache, skipping this iteration.")
            continue

        print("\n--- STEP 2: FETCH ROUTE USING COORDINATES ---")
        origin_loc = {"lat": origin_lat, "lng": origin_lng}
        dest_loc = {"lat": dest_lat, "lng": dest_lng}
        travel_mode = "DRIVE"

        route_key = f"{round(origin_lat,3)},{round(origin_lng,3)}|{round(dest_lat,3)},{round(dest_lng,3)}|{travel_mode}"
        route_data = fetch_compute_route(origin_loc, dest_loc, travel_mode)

        if route_data:
            polyline = route_data.get("polyline", {}).get("encodedPolyline", "")
            db_data["routes"][route_key] = {
                "route_key": route_key,
                "distance_meters": route_data.get("distanceMeters", 0),
                "duration_seconds": int(route_data.get("duration", "0s").replace("s", "")),
                "polyline": polyline
            }

            print("\n--- STEP 3: FIND VENUES ALONG THE ROUTE ---")
            search_along_query = "cafe"
            route_places = fetch_search_along_route(polyline, search_along_query)[:3]

            search_key = f"{polyline[:10]}_{search_along_query.lower()}"
            db_data["search_along_routes"][search_key] = route_places
            place_ids_to_process.update(route_places)

        print("\n--- STEP 4: FETCH FULL DETAILS & CRAWL WEB FOR ALL ---")
        for pid in place_ids_to_process:
            # Skip if already in current run's DB
            if pid in db_data["places"]:
                print(f"  [~] Place {pid} already in DB, skipping.")
                continue

            # Prioritize cache, only call API for new places (along route)
            raw_details = places_cache["by_id"].get(pid)
            if raw_details:
                print(f"  [cache] {pid}")
            else:
                raw_details = fetch_place_details(pid)
                if not raw_details:
                    continue
                # Save to cache for future use
                places_cache["by_id"][pid] = raw_details

            # 1. Process Reviews
            parsed_reviews = [{"rating": r.get("rating", 0), "text": r.get("text", {}).get("text", ""), "time": r.get("publishTime", "")} for r in raw_details.get("reviews", [])[:3]]

            # 2. Process Opening Hours
            opening_hours = None
            if "regularOpeningHours" in raw_details:
                opening_hours = {
                    "open_now": raw_details["regularOpeningHours"].get("openNow", False),
                    "weekday_text": raw_details["regularOpeningHours"].get("weekdayDescriptions", [])
                }

            # 3. Process Accessibility
            access_options = raw_details.get("accessibilityOptions", {})
            accessibility = {
                "wheelchairAccessibleParking": access_options.get("wheelchairAccessibleParking", False),
                "wheelchairAccessibleEntrance": access_options.get("wheelchairAccessibleEntrance", False)
            }

            # 4. Process Amenities
            amenities = {
                "allowsDogs": raw_details.get("allowsDogs", False),
                "goodForChildren": raw_details.get("goodForChildren", False),
                "servesVegetarianFood": raw_details.get("servesVegetarianFood", False),
                "outdoorSeating": raw_details.get("outdoorSeating", False)
            }

            website_url = raw_details.get("websiteUri")

            # 5. Assemble Final Object
            place_obj = {
                "place_id": raw_details.get("id"),
                "name": raw_details.get("displayName", {}).get("text", "Unknown"),
                "location": {
                    "lat": raw_details.get("location", {}).get("latitude", 0),
                    "lng": raw_details.get("location", {}).get("longitude", 0)
                },
                "address": raw_details.get("formattedAddress", ""),
                "types": raw_details.get("types", []),
                "rating": raw_details.get("rating", 0.0),
                "user_rating_count": raw_details.get("userRatingCount", 0),
                "price_level": raw_details.get("priceLevel", 1),
                "website_url": website_url,
                "phone_number": raw_details.get("nationalPhoneNumber", ""),
                "business_status": raw_details.get("businessStatus", "UNKNOWN"),
                "opening_hours": opening_hours,
                "accessibility": accessibility,
                "amenities": amenities,
                "reviews": parsed_reviews,
                "available_slots": generate_fake_slots()
            }
            db_data["places"][pid] = place_obj

            # Crawl Web if URL exists
            if website_url:
                markdown_content = fetch_webpage_content(website_url)
                if markdown_content:
                    db_data["webpages"][website_url] = {"url": website_url, "title": place_obj["name"], "content_markdown": markdown_content}

        print("\n--- STEP 5: GENERATE DYNAMIC MOCK URBAN DATA ---")
        # Attach events to Destination via ID
        generate_fake_events(db_data, [{"id": dest_id, "name": dest_name,
                                        "lat": dest_lat, "lng": dest_lng}])
        # Attach bus schedule to Origin via ID
        generate_fake_transit(db_data, [{"id": origin_id, "name": origin_name,
                                         "dest_name": dest_name,
                                         "lat": origin_lat, "lng": origin_lng}])

        crawl_idx += 1
        print(f"  [Progress] Valid webpages: {len(db_data['webpages'])}/{min_webpages}")

    if len(db_data["webpages"]) < min_webpages:
        print(f"\n[!] Reached limit of {max_crawls} iterations with only {len(db_data['webpages'])} webpages (target: {min_webpages}).")
        print("    Try increasing MAX_CRAWLS or running place_crawler.py to expand the pool.")
    else:
        print(f"\n[OK] Target of {min_webpages} webpages reached after {crawl_idx} iterations.")

    # Save cache (add newly discovered places along route)
    save_places_cache(places_cache)

    # Export accumulated data to db.json
    with open(f"db_{CITY}.json", "w", encoding="utf-8") as f:
        json.dump(db_data, f, indent=4, ensure_ascii=False)
    print(f"[OK] Saved to db_{CITY}.json | places: {len(db_data['places'])} | webpages: {len(db_data['webpages'])} | users: {len(db_data['users'])}")

if __name__ == "__main__":
    build_database(MIN_WEBPAGES, MAX_CRAWLS)